### ISSUE TITLE
Browser scrollbar

### ISSUE THREAD

**Issue by SndrL** [ahmednooor/halkaBox.js#1]
This is a very nice, well implemented lightbox. Kudos!
The only thing stopping me from using this is the disappearing/appearing scrollbar when you open the lightbox. Is this intentional? Could it maybe be optional?

**Comment by ahmednooor** [comment]
thanks a lot for the appreciation :) and yes it's intentional. it is because when the scrollbar is active and the user scrolls up or down and then closes the lightbox, the focused image or gallery gets out of the focus(center of screen). so the scroll bar is disabled when lightbox is active to prevent such action. If you want the scroll bar to be active then you can do following,
* open halkaBox.css or halkaBox.min.css
* find the .hb-noscroll class
* empty it or set the value of all properties to auto

like from this,
```css
.hb-noscroll {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
}
```
to this,
```css
.hb-noscroll {
}
```
or set the value of every property to auto like this,
```css
.hb-noscroll {
    height: auto;
    width: auto;
    overflow: auto;
}
```

I hope it will solve your problem :)
I am a newbie trying to learn JS and as i advance i will try my best to make the plugin much better while keeping it simple and lightweight at the same time :)
Thank you for your feedback :)
